name: Build V2 (Exercicio 02)

on:
  push:
    paths:
      - 'exercicio02/**'  # Só roda se mexer na pasta 02

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./exercicio02 # <--- Define a pasta para este job
    steps:
      - uses: actions/checkout@v3      # <--- PRIMEIRO PASSO SEMPRE
      - name: Install dependencies
        run: npm install               # <--- Instalação flexível
      - name: Run Lint
        run: npm run lint

  test:
    needs: lint                        # <--- Só começa se o Lint passar
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./exercicio02
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Test code
        run: npm run test

  deploy:
    needs: test                        # <--- Só começa se o Test passar
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./exercicio02
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build code
        run: npm run build
      - name: Deploy code
        run: echo "Simulando Deploy... Sucesso!"