name: Simple Local (Ex 01)
on:
  push:
    paths:
      - 'exercicio-01/**'  

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:18
    defaults:
      run:
        working-directory: ./exercicio-01  
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: node app.js