name: Simple Local (Ex 01)

on:
  push:
    paths:
      - 'exercicio01/**'  # O segredo: só roda se mexer na pasta 01

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:18
    defaults:
      run:
        working-directory: ./exercicio01  # Entra na pasta antes de rodar
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      # Se você usou o moment no ex1, mantenha, senão pode tirar esta linha:
      - run: npm install --save moment 
      - run: node app.js